//task 23
var car = "subaru";
console.log("is car == 'subaru'? predict true");
console.log(car == 'subaru');
console.log("is car !='honda city'? predict true");
console.log(car != 'honda city');
console.log("is Car == 'subaru'? predict false");
console.log(car == 'subaru');
console.log("is Car == 'SUBARU'? predict false");
console.log(car == 'SUBARU');
console.log("is car lenght ==8? predict true");
console.log(car.length == 8);
console.log("is car lenght != 10? predict true");
console.log(car.length != 10);
console.log("is 10 > 45 ? predict false");
console.log(10 > 45);
console.log("is 3 <= 2 ? predict false");
console.log(3 <= 2);
console.log("is 72 > 63 ? predict false");
console.log(72 <= 63);
console.log("is car == 'subaru? && car.length == 6? predict true");
console.log(car == 'subaru' && car.length == 6);
